### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mmarianav**
More edits , I do not like the commit traduction , but need to think about

### CODE REVIEW

**Comment by cylammarco** [comment]
Does this pull request supersede #10? Should #10 be closed and merge this one?

**Comment by mmarianav** [comment]
Yes we should close 

> Does this pull request supersede #10? Should #10 be closed and merge this one?

Yes #10 should be close and merge this one.

**Comment by michaelJwilson** [comment]
You're ready to merge this one?  Thanks!

**Comment by mmarianav** [comment]
Yes please merge this soon to clean a bit,  I did  yesterday the editing of 3 notebooks , you should be able to merge everything as are in different files.

**Pull request closed without merging**
