### PR TITLE
Edits alma

### PR DESCRIPTION
**Pull request by alxogm**
OK. I think I've finished my first round... not ready to merge though. 

I'll check for possible typos or orthographic errors, and @mmarianav please check that I did not overwrote important information added by you. I've a few questions and will marked them inline... @mmarianav please use the review tool, i.e. leave message in place and I'll fix it... it is easier. We'll merge once we are both happy. 

Thanks!

### CODE REVIEW

**Comment by mmarianav** [comment]
Ok I will check  tonight, just making sure , you overwrote some sections in particular? I thought you took my last version ...=)

**Comment by alxogm** [comment]
> Ok I will check tonight, just making sure , you overwrote some sections in particular? I thought you took my last version ...=)

Thanks @mmarianav, I merged the master branch after your PRs into my branch, favoring master over my edits most of the times when in conflict, and complementing in others... You can see here the changes https://github.com/michaelJwilson/DESI-HighSchool/pull/17/files . You can add comments in lines where you strongly disagree with a particular change. Thanks.

**Comment by michaelJwilson** [comment]
Should I merge?

**Comment by mmarianav** [comment]
I checked yesterday is fine for me . If I have more edits we can include them later. @alxogm , I prefer to add my edits directly, so please merge

**Comment by alxogm** [comment]
OK, go ahead and merge.

**Pull request merged**
