### PR TITLE
Revision of Noteboks DESI, Intro, SnowWhiteDwarf ....

### PR DESCRIPTION
**Pull request by mmarianav**
Well I am not sure of using github optimally but hopefully is ok, each pull request is for different files so should be ok

### CODE REVIEW

**Comment by mmarianav** [comment]
Please merge my changes to clean a little there is just one conflicting change in 1 line in my own changes so you can  choose whatever version of it , we will check them again later

**Comment by mmarianav** [comment]
Please merge all changes to clean a little there is no conflicts now !

**Comment by michaelJwilson** [comment]
Perfect, thanks!  Is #11  good to close now?  Can you coordinate with @alxogm on the remaining notebooks?  I think Alma has already started the new 'Designing DESI' one that wasn't in your older clone.   I'll take another sweep through the ones you just looked at as I think there were a few of examples of [this is text](this is link) being [this is text] (this is link), the former makes it a hyperlink rather than showing both, with the latter being a broken example that will show both. 

I saw mostly changes to the cell text.  All the links we're pointing to, e.g. wikipedia (repeatedly), will be in English I think.  We'll probably want to chase down alternatives that are in Spanish.  But that could take a while so let's leave it as a to do. 

Thank you, again!  Hopefully they were ok.  Looks like the Jupyter translation did pretty well.

**Comment by alxogm** [comment]
Hi @michaelJwilson , 
I'm waiting for @mmarianav  to confirm if she will do any more PRs for the day. If not, I'll make mine making sure it doesn't override any of Mariana's work, unless I think it is for the better but in which case I'll ask first. 

In my revision I've changed links to spanish versions, and also changed code comments to spanish, I see most of the work is complementary so it should be fine... Hopefully we'll finish by today.  I'm also waiting for @mmarianav  to confirm who works on the last notebook that is remaining to do...

**Comment by alxogm** [comment]
@michaelJwilson I can take care of the links too. I did noticed and fixed a few... but not all... Thanks.

**Comment by michaelJwilson** [comment]
Ok, looks like there's one remaining that @alxogm can handle?  The merge conflicts should handle any overlap anyway. 

Btw, I'm using this to generate the proto-Spanish:  https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/nbTranslate/README.html 

It's not ideal moving forward, particularly I'm not sure what's going to happen when we make a small update to an english version.  We'll want to get away from this meaning you have to start the Spanish all over again. But it might be useful for you in other circumstances anyway.

I'll be updating at least one notebook by Friday (starting with Ripples).  It's not necessary that the English and Spanish are exactly in sync - I'm more worried that the Spanish be accurate - but the closer match between the material the better.

**Comment by michaelJwilson** [comment]
Finally, the Spanish versions should ideally be added to the Travis test here:  https://github.com/michaelJwilson/DESI-HighSchool/blob/master/notebook_tester.py

It's probably overkill given the minimal changes, but it'll catch any instances where you might manage to break the code during the changes.  And the hope is for parity between English / Spanish. 

None of this is necessary by Friday.  But it'll be good for you to know aswell.

**Comment by michaelJwilson** [comment]
Using this as a forum where people are paying attention, you might want to think about some small advertisement on Friday.  We'll be sending out english versions on the DESI and LBL (Physics) twitter accounts.  Better would be to discuss it [here](https://join.slack.com/t/desihigh/shared_invite/zt-hcbl1fqp-UH60XG7IAkJBCevkDOAf_A) if anything is unclear.

**Comment by mmarianav** [comment]
@alxogm , the readme changes are merged, I understand you are complementing my changes, right? SO I am not going to touch any of the notebooks I previously edited.

**Comment by mmarianav** [comment]
@alxogm I can work now in the last notebook and then you pass over it, as we are doing with the others

**Comment by alxogm** [comment]
@mmarianav just don't work on https://github.com/michaelJwilson/DESI-HighSchool/blob/master/Espanol/DesigningDESI_es.ipynb. I've already done that... you can give feedback later when I do the PR. 

Thanks

**Comment by mmarianav** [comment]
@alxogm sure, I am done with nbody_es if you want to take a second round and let me know when I can take a look to DesigningDESI

**Pull request merged**
