### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by mmarianav**

### CODE REVIEW

**Comment by michaelJwilson** [comment]
All done?

**Comment by mmarianav** [comment]
Wait !

**Comment by michaelJwilson** [comment]
Let's get used to the draft button ;)

**Comment by mmarianav** [comment]
The problem is that I did it in the old directory and then the new directory perfil appeared

**Comment by mmarianav** [comment]
profile ---> perfil

**Comment by michaelJwilson** [comment]
Can you try deleting the profiles version and recommit.  If that doesn't work, I can just delete it myself after merging?

**Comment by mmarianav** [comment]
Now is ready alma is doing the Gustavo part

**Pull request merged**
