### PR TITLE
Merge pull request #1 from michaelJwilson/master

### PR DESCRIPTION
**Pull request by jsuarez314**
Removed duplicated in Spanish version.
Translated the SupernovaeBrain notebook.
Update the binder links to 1.2.5 git tag.
Other typo corrections.

### CODE REVIEW

**Comment by michaelJwilson** [comment]
@jsuarez314 this looks great, thank you!  I'm sure it's perfect, but tagging @alxogm as a sanity check on the translation of the new notebook.  Can you confirm that after the data structure changes, all the notebooks run on a new Binder?  Thanks for your help, hope you're having a great holiday!

**Comment by jsuarez314** [comment]
@michaelJwilson I can not confirm if the notebooks run on Binder. The notebooks could be confirmed after the pull request when the tag 1.2.5 will be uploaded in the repo. Or am I wrong?

**Comment by michaelJwilson** [comment]
You can create a new Binder instance from master on your fork at https://mybinder.org/.  Failing that, you can locally create a jupyter kernel from the environment.yml and test everything runs solely within that.  I have a vague memory we ran into problems with the Binder step on similar, but less global, past changes.  Thanks!

**Comment by alxogm** [comment]
Hi! was this merged? I see it is closed but os not clear to me it was merged... I'm back to the work this week :D

**Comment by michaelJwilson** [comment]
Yes, somewhere there was a comment to you :)  Basically, we're to finalize the new notebook (in English), after that it'd be great if you could both add the necessary changes / cross check everything.  Happy New Year!  Thanks for the help.

**Pull request closed without merging**
